### ISSUE TITLE
Test project not included in the main solution

### ISSUE THREAD

**Issue by robsmithw** [Leagify/prospect-scraper-dt2021#27]
Any reason the prospectScraperTest.csproj (test project) is not included in the prospectScraper.sln (main solution)?
I was making a change on another issue and noticed this, if the test project was part of the main solution, any contributors using Visual Studio to develop would see the test project regardless of what they're making a change to and would prompt contributors to be more likely to run the test before commiting changes (I would hope 😄).

**Comment by zo0o0ot** [comment]
I don't have any problems with getting it added.  I've been doing most of my development in GitPod, which uses the csproj files, not the sln, which is probably why I missed that.

**Comment by zo0o0ot** [comment]
This was actually handled in #26
