### ISSUE TITLE
Readme and csproj have different Frameworks

### ISSUE THREAD

**Issue by Rollerss** [Leagify/prospect-scraper-dt2021#31]
The [README.md](https://github.com/Leagify/prospect-scraper-dt2021/blob/master/README.md) has this project as .NET Core 3.1
"This program is written in .NET Core 3.1."

While [prospectScraper.csproj](https://github.com/Leagify/prospect-scraper-dt2021/blob/master/src/prospectScraper/prospectScraper.csproj) has the framework as .NET 5
'TargetFramework>net5.0</TargetFramework'

**Comment by zo0o0ot** [comment]
You're right.  That's a recent change from #18 but the documentation was not updated to reflect the change.
