### ISSUE TITLE
Add github action to build and run tests

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/prospect-scraper-dt2021#34]
I recently opened the project in GitPod and some of the stuff failed.  It would be nice to check if the project builds in Linux and can run tests in Linux.

**Comment by robsmithw** [comment]
I can tackle this pretty soon if you wanna throw this to me, I had it building and running test on another branch with github actions, but the upgrade to target .NET 5 kinda messed it up so I'll have to look at it a little bit more.

**Comment by zo0o0ot** [comment]
I know the build failed for me after the .NET 5 upgrade because the project name references had been put into PascalCase even though the file names were in camelCase.  I think that probably works in Windows and blows up in Linux. I fixed it in #35, but it would have been nice to catch before I merged the original commit that broke it.

**Comment by robsmithw** [comment]
Definitely agree there!

**Comment by robsmithw** [comment]
Right now getting this error:
Error: /home/runner/work/prospect-scraper-dt2021/prospect-scraper-dt2021/test/prospectScraperTest/ProgramTest.cs(33,50): error CS0117: 'Program' does not contain a definition for 'FormatDraftDate' [/home/runner/work/prospect-scraper-dt2021/prospect-scraper-dt2021/test/prospectScraperTest/ProspectScraperTest.csproj]
Seems like a method might've been renamed to something else, trying to look through and see what it was changed to unless you know off hand?

**Comment by zo0o0ot** [comment]
Handled in #36
