### ISSUE TITLE
Update to .NET 5

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/prospect-scraper-dt2021#40]
https://devblogs.microsoft.com/dotnet/announcing-net-5-0/

I think we're currently on the 5 RC, make any updates necessary to get onto the LTS version.

**Comment by Christian-Oleson** [comment]
Opened a PR for this as a formally, but this is already on .NET 5. I simply am updating the packages.

**Comment by Christian-Oleson** [comment]
@zo0o0ot 
This one can be closed

**Comment by zo0o0ot** [comment]
Addressed in #43
